setGeneric("rgraphBAM", function(n, param, ...) standardGeneric("rgraphBAM"))
setGeneric("UGgmm", function(g, ...) standardGeneric("UGgmm"))
setGeneric("HMgmm", function(g, ...) standardGeneric("HMgmm"))
setGeneric("rUGgmm", function(n, g, ...) standardGeneric("rUGgmm"))
setGeneric("rHMgmm", function(n, g, ...) standardGeneric("rHMgmm"))
setGeneric("eQTLcross", function(map, genes, model, ...) standardGeneric("eQTLcross"))
setGeneric("addGenes", function(eQTLcross, n, ...) standardGeneric("addGenes"))
setGeneric("addeQTL", function(eQTLcross, ...) standardGeneric("addeQTL"))
setGeneric("addGeneAssociation", function(eQTLcross, ...) standardGeneric("addGeneAssociation"))
setGeneric("reQTLcross", function(n, network, ...) standardGeneric("reQTLcross"))
setGeneric("alleQTL", function(x, ...) standardGeneric("alleQTL"))
setGeneric("ciseQTL", function(x, cisr, ...) standardGeneric("ciseQTL"))
setGeneric("transeQTL", function(x, cisr, ...) standardGeneric("transeQTL"))
setGeneric("rcmvnorm", function(n, model, ...) standardGeneric("rcmvnorm"))
